version: '3.8'

services:
  web:
    build:
      context: .
      args:
        NEXT_PUBLIC_SUPABASE_URL: https://xifchjacajqgwcdtdmfw.supabase.co
        NEXT_PUBLIC_SUPABASE_ANON_KEY: sb_publishable_JUglqvkLKkpYUg6Psaay9w_WhQKbkc-
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=https://xifchjacajqgwcdtdmfw.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=sb_publishable_JUglqvkLKkpYUg6Psaay9w_WhQKbkc-
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    restart: always
